### ISSUE TITLE
Processing GitHubRepo

### ISSUE THREAD

**Issue by msvrtan** [devboard/devboard-core#14]
- [x] Update GitHubRepo details command #15 
- events
- [x] name changed #17 
- [x] owner changed #17 
- [ ] repo became private #21
- [ ] repo became public #21
- [ ] description updated #22
- [ ] default branch changed #23
